package fileio.input.wrappedEntities;

import fileio.input.audioEntities.SongPlayInfo;

public class MonetizedSong {
    private SongPlayInfo songPlayInfo;
    private Double revenue;

    public MonetizedSong(final SongPlayInfo songPlayInfo, final Double revenue) {
        this.songPlayInfo = songPlayInfo;
        this.revenue = revenue;
    }

    /**
     * Gets the SongPlayInfo associated with this monetized song.
     *
     * @return The SongPlayInfo associated with this monetized song.
     */
    public SongPlayInfo getSongPlayInfo() {
        return songPlayInfo;
    }

    /**
     * Sets the SongPlayInfo associated with this monetized song.
     *
     * @param songPlayInfo The new SongPlayInfo to be associated with this monetized song.
     */
    public void setSongPlayInfo(final SongPlayInfo songPlayInfo) {
        this.songPlayInfo = songPlayInfo;
    }

    /**
     * Gets the revenue generated by this monetized song.
     *
     * @return The revenue generated by this monetized song.
     */
    public Double getRevenue() {
        return revenue;
    }

    /**
     * Sets the revenue generated by this monetized song.
     *
     * @param revenue The new revenue to be associated with this monetized song.
     */
    public void setRevenue(final Double revenue) {
        this.revenue = revenue;
    }
}
